// WHICH process triggered this ledger entry
export enum LedgerSource {
  INVESTMENT_CONFIRMATION = 'INVESTMENT_CONFIRMATION',
  DISTRIBUTION_ENGINE = 'DISTRIBUTION_ENGINE',
  PAYOUT_REQUEST = 'PAYOUT_REQUEST',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',
}
