export enum LedgerSource {
  // Original/Existing Sources
  INVESTMENT_CONFIRMATION = 'INVESTMENT_CONFIRMATION',
  DISTRIBUTION_ENGINE = 'DISTRIBUTION_ENGINE',
  PAYOUT_REQUEST = 'PAYOUT_REQUEST',
  PAYOUT_COMPLETED = 'PAYOUT_COMPLETED',
  PAYOUT_FAILED = 'PAYOUT_FAILED',
  ADMIN_ADJUSTMENT = 'ADMIN_ADJUSTMENT',

  // Secondary Market & Escrow Sources (Fixes your current errors)
  SECONDARY_MARKET_SELL = 'SECONDARY_MARKET_SELL',
  SECONDARY_MARKET_BUY = 'SECONDARY_MARKET_BUY',
  SECONDARY_MARKET_TRADE = 'SECONDARY_MARKET_TRADE',

  ESCROW = 'ESCROW',
  WITHDRAWAL = 'WITHDRAWAL',
  DIVIDEND_PAYOUT = 'DIVIDEND_PAYOUT',

  // New Wallet & Investment Logic
  WALLET_DEPOSIT = 'WALLET_DEPOSIT',
  ASSET_INVESTMENT = 'ASSET_INVESTMENT',
  ESCROW_LOCK = 'ESCROW_LOCK',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  DEPOSIT = 'DEPOSIT', // 👈 Add this
}
