export enum LedgerType {
  INVESTMENT = 'INVESTMENT',
  DISTRIBUTION = 'DISTRIBUTION',
  PAYOUT = 'PAYOUT',
  REFUND = 'REFUND',
  ADJUSTMENT = 'ADJUSTMENT',
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  DISPUTE_ADJUSTMENT = 'DISPUTE_ADJUSTMENT',
  ESCROW_LOCK = 'ESCROW_LOCK',
  ESCROW_RELEASE = 'ESCROW_RELEASE',
  WITHDRAWAL_REQUEST = 'WITHDRAWAL_REQUEST',
  WITHDRAWAL_PAID = 'WITHDRAWAL_PAID',
}
