export enum AuditAction {
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',

  PARTNER_APPROVED = 'PARTNER_APPROVED',
  PARTNER_REJECTED = 'PARTNER_REJECTED',

  ASSET_APPROVED = 'ASSET_APPROVED',
  ASSET_REJECTED = 'ASSET_REJECTED',

  USER_SUSPENDED = 'USER_SUSPENDED',
}
