export enum AdminAction {
  // KYC & Users
  KYC_APPROVED = 'KYC_APPROVED',
  KYC_REJECTED = 'KYC_REJECTED',
  USER_SUSPENDED = 'USER_SUSPENDED',

  // Finance (The missing pieces)
  WITHDRAW_REQ = 'WITHDRAW_REQ',
  WITHDRAW_APPROVED = 'WITHDRAW_APPROVED',
  DEPOSIT_COMPLETED = 'DEPOSIT_COMPLETED',

  // Secondary Market & Escrow
  LISTING_CREATED = 'LISTING_CREATED',
  LISTING_CANCELLED = 'LISTING_CANCELLED',
  TRADE_EXECUTED = 'TRADE_EXECUTED',
  ESCROW_LOCKED = 'ESCROW_LOCKED',
  ESCROW_RELEASED = 'ESCROW_RELEASED',
  ESCROW_DISPUTED = 'ESCROW_DISPUTED',

  // Disputes
  DISPUTE_OPENED = 'DISPUTE_OPENED',
  DISPUTE_RESOLVED = 'DISPUTE_RESOLVED',
  DISPUTE_REJECTED = 'DISPUTE_REJECTED',

  // Original Admin Actions
  APPROVE = 'APPROVE',
  REJECT = 'REJECT',
  FREEZE = 'FREEZE',
}
